# Generated by Django 5.1.5 on 2025-01-16 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='creado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
